### PR TITLE
fixed #22: Images of blog authors not loading

### LINKED ISSUE #22: Images of blog authors not loading
image

I can work on this issue if you assign it to me with Hacktoberfest tag

### PR DESCRIPTION
**Pull request by shreyansh1410**
The images of blog authors are now loading

### CODE REVIEW

**Comment by VishnuAmit** [comment]
hey @shreyansh1410 , Could you put up a video on what you did, it would be easy for me to see the changes, as i need to fix the deployment failure errors.

Show in both mobile and desktop version to see the animation works correctly.

**Comment by shreyansh1410** [comment]
Yeah, I will

**Comment by shreyansh1410** [comment]
https://github.com/user-attachments/assets/c7f64aba-c9d8-4433-863a-622fe6738bc5

**Comment by VishnuAmit** [comment]
Hey, no need to take the length of the text as width of the box. You can have a fixed size and wrap the text. 
You can show a video of mobile version as well.

```Note``` : Kindly pull the latest changes to your local machine as we have solved the deployment issue.

**Comment by shreyansh1410** [comment]
This is how it looks on web screens:

https://github.com/user-attachments/assets/4da42cd1-32ff-43d4-8309-ab3e0f1dc353

This is how it looks on mobile:

https://github.com/user-attachments/assets/135ff467-03a1-4dee-8a53-676ce74bb24f

**Comment by shreyansh1410** [comment]
I accidentally solved both the issues in this pr itself, which means it will be counted as a single pr for hacktoberfest, is there any way for me to create separate pr for both the issues?

**Comment by VishnuAmit** [comment]
Hey..looks cool.
But can you avoid that sudden jerk and make it roll smoothly. 
And in mobile version, I cant see the entire section. It just resets to the starting point (sudden jerk here too) and when i try to swipe it, its not viewing the rest of the section.

Edit: Yes. You can create a separate issue and raise your first PR there and then same goes with 2nd pr

**Pull request closed without merging**
