### PR TITLE
Google login updated

### PR DESCRIPTION
**Pull request by Sakyasekhar**
https://github.com/user-attachments/assets/fe04108b-7006-467d-b4d5-560197ffaa48

### CODE REVIEW

**Comment by VishnuAmit** [comment]
Good.

Few changes:
- In sign up page, change the text 'sign in with google' to 'sign up with google'.
**Follow this flow**
1. After successful Google sign up, it should navigate you to sign in page where you can allow to login using Google if the data is already present in mongoDB.
2. Once successfully logged in, it should redirect to dashboard page 
3. Add the sign out option inside the drop-down of my account (it's in the navbar of the dashboard).
4. Once logged out, back to the landing page.

**Comment by Sakyasekhar** [comment]
> Good.
> 
> Few changes:
> 
> * In sign up page, change the text 'sign in with google' to 'sign up with google'.
>   **Follow this flow**
> 
> 1. After successful Google sign up, it should navigate you to sign in page where you can allow to login using Google if the data is already present in mongoDB.
> 2. Once successfully logged in, it should redirect to dashboard page
> 3. Add the sign out option inside the drop-down of my account (it's in the navbar of the dashboard).
> 4. Once logged out, back to the landing page.

hi vishnu, l am attaching the video showing all the changes you requested.

https://github.com/user-attachments/assets/57193d2b-67f9-49d9-8580-0de3d9aacaf2

**Comment by VishnuAmit** [comment]
Nice @Sakyasekhar [👏](https://emojipedia.org/clapping-hands)

**Comment by Sakyasekhar** [comment]
> Nice @Sakyasekhar [👏](https://emojipedia.org/clapping-hands)

thank you! would love to work on more issues!!

**Comment by VishnuAmit** [comment]
@Sakyasekhar , I have found few issues in the signup. Shall I create one more issue with all the labels and assign it to you?

**Comment by Sakyasekhar** [comment]
> @Sakyasekhar , I have found few issues in the signup. Shall I create one more issue with all the labels and assign it to you?

Yeah assign it. Please mention the problem in signup.

**Comment by VishnuAmit** [comment]
@Sakyasekhar You can refer this issue https://github.com/VishnuAmit/LapProFix/issues/26  and if you are willing to fix it, you can comment in that issue so that I can assign you.

**Pull request merged**
