### PR TITLE
Added responsive Search bar and phone number display on Dashboard Navbar

### PR DESCRIPTION
**Pull request by Atv23**
### Changes made:
- Commented the code for Home, Best Sellers, etc.
- Added a search bar to the navbar on Dashboard window.
- Included a mobile number field next to the search bar.
- Ensured both elements are responsive and adjust well on smaller screens.
- Improved the visibility of the mobile phone icon on smaller screen.
- Set a consistent width for the dropdown menu for Phone Number display on smaller screen.
- Maintained the CSS design to align with the blue and white theme of the application.

### Screenshots:
Screenshot 2024-10-08 102955
Screenshot 2024-10-08 103016
Screenshot 2024-10-08 103100
Screenshot 2024-10-08 103120

### CODE REVIEW

**Comment by Atv23** [comment]
I believe my changes weren't responsible for the deployment failure, as it seems to be related to resource limits on the hosting platform.

**Comment by VishnuAmit** [comment]
@Atv23 . The resource is limited and i am sorting it out and its not your mistake.

Just one small change:
image

Make the location search bar  look like this 

Put the phone number inside the hamburger. Inside hamburger: call icon - phone number

Since there are issues with deployment, you can add a video demonstrating the responsiveness.

Thanks.

**Comment by VishnuAmit** [comment]
I have updated my last comment. I think in this way, the location bar would be wider in mobile screen. Refering your 3rd image.

**Comment by Atv23** [comment]
I cant find the issue anywhere in the repo? What happened? You didnt accept
the PR also

**Comment by VishnuAmit** [comment]
https://github.com/VishnuAmit/LapProFix/issues/11. You can find the issue here. 
I didnt' accept the PR because few changes are needed to be done. 


> @Atv23 . The resource is limited and i am sorting it out and its not your mistake.
> 
> Just one small change: image
> 
> Make the location search bar look like this
> 
> Put the phone number inside the hamburger. Inside hamburger: call icon - phone number
> 
> Since there are issues with deployment, you can add a video demonstrating the responsiveness.
> 
> Thanks.

**Comment by Atv23** [comment]
Ok got it, will work on it, thanks!!
Does the search bar has to be functional too?

**Comment by VishnuAmit** [comment]
Umm, Not needed for now. But the idea is when we enter any permitted location on the search bar, it should load and display the same content, If not it should display a page `Oops, We didnt expand our services to your location yet!`

Its your wish, if you are willing to do this as well in the same issue. (Optional)

**Comment by Atv23** [comment]
the sign in has some issues with the current commit I guess, not able to access the dashboard section

**Comment by VishnuAmit** [comment]
Hey @Atv23 Sorry. we are fixing it. As of now, you could connect it to your mongoDB database and paste the connection string in db->config.js. 
 
 Following that, try to sign up and then sign in (only google works now) , then you can access the dashboard page.
 User your google id and secret in your .env file.
 
 Sorry for this. Let me know if you can reach the dashboard page.

**Comment by VishnuAmit** [comment]
@Atv23 It's fixed. You can signup/signin and access the dashboard page. Connect it your mongodb.

**Comment by Atv23** [comment]
Sorry for the delay but the Signin/Signup still wasn't functioning whenever I tried, I changed home page path and disabled session to make the changes which I ensured to change it back. Please consider the change, I requested a PR

**Pull request closed without merging**
