### PR TITLE
contribution file add

### PR DESCRIPTION
**Pull request by Mukesh-ghildiyal**
#13  done

### CODE REVIEW

**Comment by VishnuAmit** [comment]
Looks great. Can you add the link to the contribution.md file in a suitable location so that users can see the content of that file as well.

It's your choice. Either using hyperlink or combining both in a single readme.md file, as GitHub allows to display only readme.md file by default.

**Comment by Mukesh-ghildiyal** [comment]
Ok so I just add contribution file with read me file is it okk??

**Comment by VishnuAmit** [comment]
Yea, that would be fine as long as it's not too lengthy. The contents of the contribution.md file will be displayed first followed by the readme.md file. Maintain the smooth flow of reading for the users from the beginning to the end.

**Comment by Mukesh-ghildiyal** [comment]
check it now

**Pull request merged**
