### PR TITLE
Made changes required to Navbar of Dashboard

### PR DESCRIPTION
**Pull request by Atv23**
https://github.com/user-attachments/assets/56863a0c-7ae4-478d-9321-6cf39d39b1de

### Changes Done

- Modified Search Bar: Updated the search bar to include a location pin icon at the start and a wider input field.
- Moved 'Call Us' to Hamburger Menu: On smaller screens, moved the 'Call Us' option into a hamburger menu for better responsiveness.
- Responsive Layout: Ensured that the search bar and navbar elements adjust properly as the screen size shrinks, maintaining a clean layout.
- Ensured Icon Alignment: Fixed alignment issues for the location and search icons within the search bar to prevent overlap or misplacement on screen resize.

>Sorry for the delay but the Signin/Signup still wasn't functioning whenever I tried, I changed home page path and disabled session to make the changes which I ensured to change it back. Please consider this change

### CODE REVIEW

**Comment by VishnuAmit** [comment]
Hey @Atv23 I can see that working. Give me couple of hours to preview this as the daily limit has got over. 
Have you pulled all the new commits?

**Comment by Atv23** [comment]
yep, made changes in the latest commit

**Comment by Atv23** [comment]
Could you please look into the change and accept my PR under HacktoberFest24 participation, it will mean a lot. Thanks!

**Comment by VishnuAmit** [comment]
Hey. sorry i was waiting to preview it but didn't get resource to look yours. That's the reason I didn't accept yours yet.
Just one small change: 
Don't shrink the my cart text instead reduce the length of the search box. It is not required to have the maximum available width.

Edit: Just run this command ``pnpm install`` in your terminal and raise a pr to resolve the deployment error. By this way, I can preview yours.

**Comment by VishnuAmit** [comment]
Hey @Atv23 . Ill do the rest by myself. If you are interested to contribute again, do checkout the issues or create any if you feel you can improve on that thing.

**Comment by Atv23** [comment]
Sure, thanks a lot

**Pull request merged**
