### PR TITLE
Added Forgot Password Functionality

### PR DESCRIPTION
**Pull request by MahendraPachipala**
#### Description:
This pull request introduces the functionality to send an OTP to the user's email address upon request, ensuring the user exists in the database before generating the OTP. It also enhances error handling for cases where the user does not exist or if there are issues sending the OTP email.

#### Changes Made:
1. **Created an Endpoint**: Added a new endpoint for sending OTP at `/api/email/forgotpassword`.
2. **Database Integration**: Integrated MongoDB to verify user existence and save the OTP, which will be automatically deleted after 5 minutes.
3. **Nodemailer Setup**: Configured Nodemailer to send emails through Gmail, including necessary authentication.
5. **HTML Email Content**: Added HTML formatting to the email sent to users, including a security note advising them not to share the OTP.

#### Email Configuration:
To configure Nodemailer, follow these steps to generate a new app password:

**Option 1: Step-by-Step Instructions**
1. Go to your Google account dashboard.
2. Navigate to the "Security" tab.
3. Search for "App passwords" and generate a new password.

**Option 2: Direct Link**
- Generate a new password by visiting [this link](https://security.google.com/settings/security/apppasswords).

<p style="color:red;">Ensure that 2-Step Verification is enabled on your Google account before generating the password, as you will not be able to create an app password without it.</p>

Set the following environment variables in your `.env` file:
```plaintext
EMAIL_USER="Your email here to send OTP"
EMAIL_PASS="Your email application password"

### CODE REVIEW

**Comment by VishnuAmit** [comment]
Hey @MahendraPachipala Good work again. Give me some time before reviewing it. In the meantime, you can attach a video of your work.

**Comment by MahendraPachipala** [comment]
> Hey @MahendraPachipala Good work again. Give me some time before reviewing it. In the meantime, you can attach a video of your work.

ok

**Comment by MahendraPachipala** [comment]
Uploading localhost_3000_signin - Google Chrome 2024-10-13 15-35-23.mp4…

**Comment by MahendraPachipala** [comment]
https://github.com/user-attachments/assets/1de24914-b618-4274-a579-f6deb269461a

**Comment by VishnuAmit** [comment]
So, it does update the password in the local database once it has been reset to new. right? Ill test it and let you know. Please give me some time.

**Comment by MahendraPachipala** [comment]
> So, it does update the password in the local database once it has been reset to new. right? Ill test it and let you know. Please give me some time.

Yes, once the OTP is successfully verified, the new password will be updated in the local database. The reset process involves checking the OTP for validation, and if it matches and is still valid (within its expiration time), the user will be able to reset their password. After the new password is submitted, it will overwrite the old one in the database.

Take your time to test it, and feel free to reach out if you need any further clarifications or run into any issues!

**Pull request merged**
